version: '3.8'

services:
  app-bind:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data  
    ports:
      - "8080:8080"
  
  app-volume:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app_data:/app/data  
    ports:
      - "8081:8080"

volumes:
  app_data:  
